services:
  app:
    image: autotests-api:latest
    container-name: autotests-api
    ports:
      - "8080:8081"
    environment:

    build: .    
  
  tests:
    build: .
    volumes:
      -  ./artifcts/allure-results:/app/allure-reports
